name: cfn-nag Scan

on: [push]

jobs:
  ## cfn-nag security scan
  security-scan-cfn-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stelligent/cfn_nag@master
      with:
        input_path: MonoToMicroAssets

